require: sudo
language: node_js
services:
  - docker
env:
  - DOCKER_IMAGE=prodest/api-cloud
script: 
  docker build -t $DOCKER_IMAGE .
deploy:
  provider: script
  script: travis.sh
  on:
    branch: master
